version: 2

models:
  - name: stg_customers
    description: "Staging model for customers"
    columns:
      - name: cust_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: "Staging model for orders"
    columns:
      - name: od_id
        tests:
          - unique
          - not_null
  - name: stg_order_items
    description: "Staging model for order items"
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
  - name: stg_products
    description: "Staging model for products"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
